import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f9f9f9", paddingTop: 20 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    color: "#ff1493",
    marginBottom: 15,
  },
  searchInput: {
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 12,
    fontSize: 16,
    marginBottom: 15,
    marginHorizontal: 15,
    borderWidth: 0.8,
    borderColor: "#ffd6e8",
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    marginHorizontal: 0,
  },
  itemCard: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 12,
    borderWidth: 0.8,
    borderColor: "#ffd6e8",
  },
  itemBought: {
    backgroundColor: "#ffb6c1",
  },
  itemText: { fontSize: 16, color: "#000" },
  itemTextBought: {
    fontSize: 16,
    color: "#fff",
    textDecorationLine: "line-through",
  },
  itemActions: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 10,
    gap: 10,
  },
  emptyContainer: { alignItems: "center", marginTop: 50 },
  emptyText: { fontSize: 16, color: "#bbb", marginTop: 10 },
  addContainer: {
    position: "absolute",
    bottom: 20,
    left: 15,
    right: 15,
    flexDirection: "row",
    alignItems: "center",
  },
  addInput: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 12,
    fontSize: 16,
    marginRight: 10,
    borderWidth: 0.8,
    borderColor: "#ffd6e8",
  },
  addButton: {
    backgroundColor: "#ff1493",
    padding: 15,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
});
